spring.application.name=videojuegos_examen
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp

spring.datasource.url = jdbc:mysql://localhost:3306/videojuegos_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=ralo1212
spring.jpa.hibernate.ddl-auto=update
spring.mvc.hiddenmethod.filter.enabled=true